item/urls.py
from django.urls import path
from .views import (ItemCreate, Itemlistview, Itemcompleteview, Itemdetailview, Itemdeleteview, Itemdeleteview_complete, Itemupdateview, 
ClosetCreateView, ClosetCreateCompleteView, ClosetListView, ClosetUpdateView, ClosetUpdateCompleteView, SeasonGateView, SeasonListHomeView, 
OccasionGateView, OccasionListHomeView, TestView, ClosetChangeView, ClosetDeleteView, ClosetDeleteCompleteView,
)


urlpatterns = [
    path('item-create/', ItemCreate, name = 'item_create'),
    path('item-list/', Itemlistview, name = 'item_list'),
    path('item-complete/', Itemcompleteview, name = 'item_complete'),
    path('item-detail/<int:pk>/', Itemdetailview, name = 'item_detail' ),
    path('item-delete/<int:pk>/', Itemdeleteview, name = 'item_delete'),
    path('item-delete-confirm/<int:pk>/', Itemdeleteview, name = 'item_delete_confirm'),
    path('item-delete_complete/', Itemdeleteview_complete, name = 'item_delete_complete'),
    path('item-update/<int:pk>/', Itemupdateview, name = 'item_update'),
    path('closet-create/', ClosetCreateView, name = 'closet_create'),
    path('closet-create-complete/', ClosetCreateCompleteView, name = 'closet_create_complete'),
    path('closet-list/', ClosetListView, name = 'closet_list'),
    path('closet-update/<int:pk>/', ClosetUpdateView, name = 'closet_update'),
    path('closet-update-complete/', ClosetUpdateCompleteView, name = 'closet_update_complete'),
    path('closet-delete/<int:pk>/', ClosetDeleteView, name = 'closet_delete'),
    path('closet-delete-confirm/<int:pk>/', ClosetDeleteView, name = 'closet_delete_confirm'),
    path('closet-delete-complete/', ClosetDeleteCompleteView, name = 'closet_delete_complete'),
    path('season-gate/', SeasonGateView, name = 'season_gate'),
    path('season-list-home/<str:season>/', SeasonListHomeView, name = 'season_list_home'),
    path('occasion-gate/', OccasionGateView, name = 'occasion_gate'),
    path('occasion-list-home/<str:occasion>/', OccasionListHomeView, name = 'occasion_list_home'),
    path('closet-change/', ClosetChangeView, name = 'closet_change'),
    path('testview/', TestView, name = 'testview'),
    ] 

yourtansuu2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from account.views import topview


urlpatterns = [
    path('', topview, name = 'top' ),
    path('account/', include('account.urls')),
    path('contents/', include('item.urls')),
    path('customerservice/', include('customerservice.urls')),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

item/models.py
import datetime
from django.utils import timezone
from django.db import models
from django.conf import settings

class Closet(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='ユーザー', on_delete=models.CASCADE,null=True)
    closet_name = models.CharField(verbose_name='クローゼット名', max_length=255)
    closet_memo = models.CharField(verbose_name='メモ', max_length=325)
    create_date = models.DateTimeField(verbose_name='作成日', auto_now_add=True)

    class Meta:
        ordering = ['closet_name']

    def __str__(self):
        return self.closet_name

    @property
    def item_count(self):
        item_count= Item.objects.filter(closet=self).count()
        return item_count



ITEM_TYPE_CHOICES = [('jacket','上着'),('shirt','シャツ'),('pants','パンツ'),('underpants','下着(下)'),('undershirt','下着(上)'),('socks','靴下'),('others','その他')]
SEASON_CHOICES = [('spring','春'),('summer','夏'),('fall','秋'),('winter','冬')]
OCCASION_CHOICES = [('daily_use','普段着'),('work_wear','仕事'),('active_wear','よそ行き'),('sports_wear','スポーツ'),('other_use','その他')]
ITEM_COLOR_CHOICES = [('red','赤'),('blue','青'),('green','緑'),('yellow','黄'),('purple','紫'),('orange','橙'),('black','黒'),('white','白'),('grey','灰'),('beige','ベージュ'),('navy','ネイビー'),('brown','茶'),('others','その他')]
FAVORITE_LEVEL_CHOICES = [(1,'めちゃ低い'),(2,'低い'),(3,'普通'),(4,'高い'),(5,'めちゃ高い')]
ITEM_IMPORTANCE_CHOICES = [(1,'捨てれる'),(2,'悩む'),(3,'普通'),(4,'まあ大事'),(5,'めっちゃ大事')]

class Item(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='ユーザー', on_delete=models.CASCADE,null=True)
    data_id = models.AutoField(verbose_name = 'アイテムNo.', primary_key=True)
    item_type = models.CharField(verbose_name = 'アイテム種類', max_length=255, choices = ITEM_TYPE_CHOICES)
    season = models.CharField(verbose_name = '季節', max_length=10, choices = SEASON_CHOICES, default='spring')
    occasion = models.CharField(verbose_name = 'シーン', max_length=30, choices = OCCASION_CHOICES, default='daily_use')
    item_name = models.CharField(verbose_name = 'アイテム名称', max_length=300)
    item_color = models.CharField(verbose_name = 'アイテム色', max_length=20, choices = ITEM_COLOR_CHOICES, blank=True, null=True)
    item_brand = models.CharField(verbose_name = 'ブランド', max_length=150, blank=True,null=True)
    purchase_date = models.DateTimeField(verbose_name = '購入日', blank=True, null=True)
    pricing = models.IntegerField(verbose_name = '購入価格(円)', )
    purchase_place = models.CharField(verbose_name = '購入場所', max_length=255,blank=True,null=True)
    item_image = models.ImageField(verbose_name = 'アイテム画像', upload_to='images/closet', blank = True, null=True)
    memo = models.TextField(verbose_name = 'メモ', blank=True,null=True)
    favorite_level = models.IntegerField(verbose_name = 'お気に入り度', choices = FAVORITE_LEVEL_CHOICES, blank=True, null=True, default='1')
    item_importance = models.IntegerField(verbose_name = '大事さ', choices = ITEM_IMPORTANCE_CHOICES, blank=True, null=True, default='1')
    create_date = models.DateTimeField(verbose_name = '作成日', auto_now_add=True)
    update_date = models.DateTimeField(verbose_name = '更新日', auto_now=True)
    closet = models.ForeignKey(Closet, on_delete=models.PROTECT, null=True, default=None)

    class Meta:
        ordering = ['purchase_date']

    @property
    def aging_date(self):
        purchase_date = self.purchase_date
        gap_date = timezone.now() - purchase_date
        return (gap_date)

    @property
    def item_count_item(self):
        item_count_item = Item.objects.filter(item_type=self).count()
        return item_count_item

    @property
    def total_amount(self):
        pricing = self.pricing
        return (pricing)
    
    def __str__(self):
        return self.item_name

templates/contents/base_nosidebar.html
{% extends 'base.html' %}
{% load django_bootstrap5 humanize custom_pagination static %}

{% block navbar %}
<header>
  <div class = "container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <p><a class="navbar-brand" href="{% url 'home' %}">YourTansuu2</a></p>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                  <p><a class="nav-link" href="{% url 'user_information' request.user.pk %}">アカウント情報</a></p>
              </li>
              <li class="nav-item">
                <p><a class="nav-link" href="{% url 'inquiry_form' %}">お問合わせ</a></p>
              </li>
              <li class="nav-item">
                <p><a class="nav-link" href="{% url 'logout' %}">ログアウト</a></p>
              </li>
              <li class="nav-item">
                <p><a class="nav-link" href="{% url 'home' %}">ホームに戻る</a></p>
              </li>
              <li class="nav-item">
                <p><a class="nav-link" href="{% url 'top' %}">トップに戻る</a></p>
              </li>
            </ul>
          </div>
        </div>
    </nav>
  </div>
</header>
{% endblock navbar%}

<img src="{% static 'account-static/Blank_image.jpeg' %}" class="figure-img img-fluid rounded text_center space_top space_bottom" style="max-height: 150px;">



        

templates/contents/closet_complete.html
{% extends 'contents/base.html' %}
{% load django_bootstrap5 %}

{% block header %}
<div class = "container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <h2><a class="navbar-brand" href="#">YourTansuu2</a></h2>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                  <h5><a class="nav-link" href="{% url 'account_control' %}">アカウント情報</a></h5>
              </li>
              <li class="nav-item">
                <h5><a class="nav-link" href="#">お問合わせ</a></h5>
              </li>
              <li class="nav-item">
                <h5><a class="nav-link" href="{% url 'original_logout' %}">ログアウト</a></h5>
              </li>
              <li class="nav-item">
                <h5><a class="nav-link" href="{% url 'index' %}">ホームに戻る</a></h5>
              </li>
              <li class="nav-item">
                <h5><a class="nav-link" href="{% url 'home' %}">トップに戻る</a></h5>
              </li>
            </ul>
          </div>
        </div>
    </nav>
    </div>
{% endblock header %}



{% block content %}
<div class="container">
<h1>アイテム登録成功(仮画面)</h1>
<h5>リストに登録しました！</h5>
<a href="{% url 'closet_list' %}"button class="w-100 btn btn-lg btn-primary" type="submit">一覧で確認する</a>
<a href="{% url 'index' %}"button class="w-100 btn btn-lg btn-primary" type="submit">ホームに戻る</a>
</div>
{% endblock content %}

templates/contents/closet_confirm.html
{% extends 'contents/base.html' %}

{% block header %}
<div class = "container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <h2><a class="navbar-brand" href="#">YourTansuu2</a></h2>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                  <h5><a class="nav-link" href="{% url 'account_control' %}">アカウント情報</a></h5>
              </li>
              <li class="nav-item">
                <h5><a class="nav-link" href="#">お問合わせ</a></h5>
              </li>
              <li class="nav-item">
                <h5><a class="nav-link" href="{% url 'original_logout' %}">ログアウト</a></h5>
              </li>
              <li class="nav-item">
                <h5><a class="nav-link" href="{% url 'index' %}">ホームに戻る</a></h5>
              </li>
              <li class="nav-item">
                <h5><a class="nav-link" href="{% url 'home' %}">トップに戻る</a></h5>
              </li>
            </ul>
          </div>
        </div>
    </nav>
    </div>
{% endblock header%}

{% block content %}
{{ block.super }}
<div class = "container">
<h1>入力内容確認</h1>
<table class="table">
    <tr>
        <th>アイテム種類：</th>
        <td>{{ form.instance.get_item_type_display }}</td>
    </tr>
    <tr>
        <th>季節：</th>
        <td>{{ form.instance.get_season_display }}</td>
    </tr>
    <tr>
        <th>シーン：</th>
        <td>{{ form.instance.get_occasion_display }}</td>
    </tr>
    <tr>
        <th>アイテム名称：</th>
        <td>{{ form.item_name.value }}</td>
    </tr>
    <tr>
        <th>アイテム色：</th>
        <td>{{ form.instance.get_item_color_display }}</td>
    </tr>
    <tr>
        <th>アイテムブランド：</th>
        <td>{{ form.item_brand.value }}</td>
    </tr>
    <tr>
        <th>購入日：</th>
        <td>{{ form.purchase_date.value }}</td>
    </tr>
    <tr>
        <th>購入価格：</th>
        <td>{{ form.pricing.value }}円</td>
    </tr>
    <tr>
        <th>アイテム画像：</th>
        <td>{{ form.item_image.value }}</td>
    </tr>
    <tr>
        <th>メモ：</th>
        <td>{{ form.memo.value }}</td>
    </tr>
    <tr>
        <th>お気に入り度：</th>
        <td>{{ form.instance.get_favorite_level_display }}</td>
    </tr>
    <tr>
        <th>大事さ：</th>
        <td>{{ form.instance.get_item_importance_display }}</td>
    </tr>
</table>
<form action = '.' method="post">
    {% csrf_token %}
    {% for field in form %}
    {{ field.as_hidden }}
    {% endfor %}
    <input type = 'hidden' name = 'action' value='complete'>
<button class="btn btn-lg btn-primary">登録する</button>
</form>
<form action = '.' method="post">
    {% csrf_token %}
    {% for field in form %}
    {{ field.as_hidden }}
    {% endfor %}
    <input type = 'hidden' name = 'action' value='input'>
<button class="w-100 btn btn-lg btn-primary">入力に戻る</button>
</form>

</div>


{% endblock content %}

templates/contents/closet_create.html
{% extends 'contents/base_nosidebar.html' %}
{% load django_bootstrap5 %}

{% block no_sidebar_content %}
<div class="container">
{{ form.errors }}
<form action='' method='POST' enctype="multipart/form-data">
    <legend class="text_center space_top">クローゼット作成機能</legend>
    <div class="alert alert-success" style="text-align: center;">
        <p>クローゼットはアイテムを登録する"フォルダー"のことです</p>
        <p>クローゼット1つあたり、最大30件のアイテムを登録することが出来ます</p>
        <p>クローゼットの使用は任意です。作っても作らなくても構いません</p>
        <p>クローゼットが不要な方は、<a href="{% url 'item_create' %}" type="submit">アイテム新規登録</a>からアイテム登録へお進みください</p>
    </div>{% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button button_type="submit" content="クローゼット作成" %}
</form>
<a href="{% url 'home' %}" class="btn btn-md btn-info space_top" type="submit">ホームに戻る</a>
</div>
{% endblock no_sidebar_content %}

templates/contents/closet_create_complete.html
{% extends 'contents/base_nosidebar.html' %}
{% load django_bootstrap5 static %}


{% block no_sidebar_content %}
<div class="container">
    <legend class="text_center space_top">クローゼットを作成しました。</legend>
    <img src = "{% static 'account-static/closet_complete.jpg' %}" width="70%" height="30%" margin = "40px">
    <h4>どんどんアイテムを登録しましょう</h4>
    <a href="{% url 'item_create' %}" class=" btn btn-md btn-primary" type="submit">アイテムを登録する</a>
</div>
{% endblock no_sidebar_content %}

templates/contents/closet_delete_complete.html
{% extends 'contents/base_nosidebar.html' %}
{% load django_bootstrap5 %}

{% block header %}{% endblock header %}

{% block content %}
<div class="container">
    <legend>削除しました</legend>
   
<a href="{% url 'home' %}" class="w-100 btn btn-md btn-primary">ホームに戻る</a>
</div>


{% endblock content %}

templates/contents/closet_list.html
{% extends 'contents/base.html' %}
{% load django_bootstrap5 %}

{% block header %}
{% endblock header %}


{% block content %}
<div class="container">
  <legend class="text_center space_top">クローゼット一覧</legend>
  {% if page_object %}
  <table class="table">
    <thead>
      <tr>
        <th>No.</th>
        <th>クローゼット名称:</th>
        <th>クローゼット作成日:</th>
        <th>アイテム登録件数:</th>
        <th>クローゼットへ</th>
        <th>クローゼットを削除</th>
      </tr>
    </thead>
    <tbody>
      {% for item in page_object %}
      <tr>
        <td>{{ forloop.counter0 | add:page_object.start_index }}</td>
        <td><a href="{% url 'closet_update' item.pk %}">{{ item.closet_name }}</a></td>
        <td>{{ item.create_date |  date:"Y年m月d日(D)" }}</td>
        <td>登録されているアイテムは{{ item.item_count }}件です</td>
        <td><a href="{% url 'item_list' %}?closet={{ item.pk }}" button class="btn btn-sm btn-primary" type="submit">クローゼットの中をみる</a></td>
        <td><a href="{% url 'closet_delete' item.pk %}" button class="btn btn-sm btn-primary" type="submit">クローゼットを削除する</a></td>
      </tr>
      {% endfor %}
    </tbody>
    {% else %}
    <p>まだアイテムが登録されていません</p>
    {% endif %}
</table>

  <div class="pagination">
    <span class="step-links">
      {% if page_object.has_previous %}
      <a href="?page=1">&laquo; 1ページ目に戻る</a>
      <a href="?page={{ page_object.previous_page_number }}">前のページ</a>
      {% endif %}
      
      <span class="current">
        ページ {{ page_object.number }} / {{ page_object.paginator.num_pages }}
      </span>
      {% if page_object.has_next %}
      <a href="?page={{ page_object.next_page_number }}">次のページ</a>
      <a href="?page={{ page_object.paginator.num_pages }}">最後のページ &raquo;</a>
      {% endif %}
    </span>
  </div>
<a href="{% url 'home' %}" class="btn btn-md btn-info space_top" type="submit">ホームに戻る</a></button>
</div>
{% endblock content %}

templates/contents/closet_update_complete.html
{% extends 'contents/base_nosidebar.html' %}
{% load django_bootstrap5 static %}

{% block no_sidebar_content %}
<div class="container">
   <legend class="text_center space_top">クローゼット名の編集が完了しました。</legend>
   <div class="container" style="text-align: center;">
      <img src = "{% static 'account-static/closet_complete.jpg' %}" width="70%" height="30%" margin = "40px">
   </div>
<a href="{% url 'closet_list' %}" class="btn btn-md btn-primary space_bottom" type="submit">クローゼットリストに戻る</a><br>
<a href="{% url 'home' %}" class="btn btn-md btn-info" type="submit">ホームに戻る</a>
</div>
{% endblock no_sidebar_content %}

templates/contents/item_confirm.html
{% extends 'contents/base_nosidebar.html' %}
{% load django_bootstrap5 static humanize %}


{% block no_sidebar_content %}
<div class = "container">
    <legend class="text_center space_top">入力内容を確認してください</legend>
    <div class="container">
        <div class="row">
            <div class="col">
                <p class="font_confirm space_top">アイテム名称 <span class="remark"> (※必須)：</span><span class="underline">{{ form.item_name.value }}</span></p>
                <p class="font_confirm space_top">アイテム種類 <span class="remark">(※必須)：</span><span class="underline">{{ form.instance.get_item_type_display }}</span></p>
                <p class="font_confirm space_top">季節 <span class="remark">(※必須)：</span><span class="underline">{{ form.instance.get_season_display }}</span></p>
                <p class="font_confirm space_top">シーン <span class="remark">(※必須)：</span><span class="underline">{{ form.instance.get_occasion_display }}</span></p>
                <p class="font_confirm space_top">購入金額 <span class="remark">(※必須)：</span><span class="underline">{{ form.pricing.value | intcomma }}円</span></p>
                <p class="font_confirm space_top">購入日 <span class="remark">(※必須)：</span><span class="underline">{{ form.purchase_date.value }}</span></p>
                <p class="font_confirm space_top">クローゼット：<span class="underline">{{ form.closet.value }}</span></p>
                <p class="font_confirm space_top">アイテムカラー：<span class="underline">{{ form.instance.get_item_color_display }}</span></p>
                <p class="font_confirm space_top">ブランド：<span class="underline">{{ form.item_brand.value }}</span></p>
                <p class="font_confirm space_top">購入場所：<span class="underline">{{ form.purchase_place.value }}</span></p>
                <p class="font_confirm space_top">お気に入り度：<span class="underline">{{ form.instance.get_favorite_level_display }}</span></p>
                <p class="font_confirm space_top">大事さ：<span class="underline">{{ form.instance.get_item_importance_display }}</span></p>
                <p class="font_confirm space_top">メモ：<span class="underline">{{ form.memo.value }}</span></p>
            </div>
            <div class="col">
                <p class="font_confirm space_top">アイテム画像</p>
                <img src="{{ item_image_base64 }}" style="max-width: 300px;" />
                {{ form.item_image.value }}
                {% if form.item_image.value == None %}
                <img src="{% static 'account-static/Blank_image.jpeg' %}" class="figure-img img-fluid rounded text_center" style="max-width: 300px;">
                {% endif %}
            </div>
        </div>
    </div>
    <form action = '.' method="post">
        {% csrf_token %}
        {% for field in form %}
        {{ field.as_hidden }}
        {% endfor %}
        <input type = 'hidden' name = 'action' value='complete'>
        <input type="hidden" name="item_image_base64" value="{{ item_image_base64 }}" />
        <button class="btn btn-md btn-primary space_bottom">登録する</button>
    </form>
    <form action = '.' method="post">
        {% csrf_token %}
        {% for field in form %}
        {{ field.as_hidden }}
        {% endfor %}
        <input type = 'hidden' name = 'action' value='input'>
        <button class="btn btn-md btn-info">入力ページに戻る</button>
    </form>
</div>


{% endblock no_sidebar_content %}

templates/contents/item_delete.html
{% extends 'contents/base_nosidebar.html' %}
{% load django_bootstrap5 %}

{% block no_sidebar_content %}
<div class="container">
    <legend class="text_center space_top">以下のアイテムを削除しますか？</legend>
    <form action='' method="POST">{% csrf_token %}
        {% for item in object_item %}
        <ul>
            <li>アイテム種類：{{ item.get_item_type_display }}</li>
            <li>季節：{{ item.get_season_display }}</li>
            <li class="table-light">シーン：{{ item.get_occasion_display }}</li>
            <li class="table-light">アイテム名称：{{ item.item_name }}</li>
            <li class="table-light">アイテムカラー：{{ item.get_item_color_display }}</li>
            <li class="table-light">ブランド：{{ item.item_brand }}</li>
            <li class="table-light">購入日：{{ item.purchase_date }}</li>
            <li class="table-light">購入価格：{{ item.pricing }}</li>
            <li class="table-light">購入場所：{{ item.purchase_place }}</li>
            <li class="">メモ：{{ item.memo }}</li>
            <li class="table-light">お気に入り度：{{ item.get_favorite_level_display }}</li>
            <li class="table-light">大事さ：{{ item.get_favorite_level_display }}</li>
            </ul>
        {% endfor %}
        <button type = "submit" name = "button"  value = "confirm">削除します</button>
    </form>
<a href="{% url 'home' %}" class="btn btn-md btn-info">ホームに戻る</a>

</div>


{% endblock no_sidebar_content %}

templates/contents/item_delete_complete.html
{% extends 'contents/base_nosidebar.html' %}
{% load django_bootstrap5 %}

{% block no_sidebar_content %}
<div class="container">
    <form action='' method="POST">
        {% csrf_token %}
        <legend class="text_center space_top">指定したアイテムを削除しました。</legend>
    </form>
    <a href="{% url 'item_list' %}" class="btn btn-md btn-primary space_bottom" type="submit">アイテム一覧に戻る</a><br>
    <a href="{% url 'home' %}" class="btn btn-md btn-info" type="submit">ホームに戻る</a>
</div>
{% endblock no_sidebar_content %}

templates/contents/item_delete_confirm.html
{% extends 'contents/base_nosidebar.html' %}
{% load django_bootstrap5 %}


{% block no_sidebar_content %}
<div class="container">
    <form action='' method="POST">
        {% csrf_token %}
        <legend class="text_center space_top">削除確認画面</legend>
        <h5 class="text_center space_top">本当に削除しますか???</h5>
        <form action='' method="POST">{% csrf_token %}
          {% for item in object_item %}
          <ul>
              <li>アイテム種類：{{ item.get_item_type_display }}</li>
              <li>季節：{{ item.get_season_display }}</li>
              <li class="table-light">シーン：{{ item.get_occasion_display }}</li>
              <li class="table-light">アイテム名称：{{ item.item_name }}</li>
              <li class="table-light">アイテムカラー：{{ item.get_item_color_display }}</li>
              <li class="table-light">ブランド：{{ item.item_brand }}</li>
              <li class="table-light">購入日：{{ item.purchase_date }}</li>
              <li class="table-light">購入価格：{{ item.pricing }}</li>
              <li class="table-light">購入場所：{{ item.purchase_place }}</li>
              <li class="">メモ：{{ item.memo }}</li>
              <li class="table-light">お気に入り度：{{ item.get_favorite_level_display }}</li>
              <li class="table-light">大事さ：{{ item.get_favorite_level_display }}</li>
              </ul>
          {% endfor %}
    <input type = "submit" value = '本当に削除する'>
       </form>
<a href="{% url 'home' %}" class="btn btn-md btn-info" type="submit">ホームに戻る</a>
</div>


{% endblock no_sidebar_content %}

templates/contents/occasion_list.html
{% extends 'contents/base.html' %}
{% load django_bootstrap5 %}

{% block content %}
<div class="container">
  {% if page_object %}
    <p>現在表示中のシーンは{{ kikai }}です</p>
    <p>登録アイテム数：{{ page_object | length }}件</p>
    <table class="table">
      <thead>
        <tr>
          <th>No.</th>
          <th>アイテム名称：</th>
          <th>アイテム種類：</th>
          <th>アイテムカラー：</th>
          <th>購入日：</th>
          <th>詳細へ：</th>
        </tr>
      </thead>
      <tbody>
        {% for item in page_object %}
        <tr>
          <th>{{ forloop.counter0 | add:page_object.start_index }}</th>
          <th>{{ item.item_name }}</th>
          <th>{{ item.get_item_type_display}}</th>
          <th>{{ item.get_item_color_display}}</th>
          <th>{{ item.purchase_date | date:"Y年m月d日(D)" }}</th>
          <th><a href="{% url 'item_detail' item.pk %}"button class="btn btn-sm btn-primary" type="submit">詳細を見る</a></th>
        </tr>
        {% endfor %}
      </tbody>
      {% else %}
      <p>まだアイテムが登録されていません</p>
      {% endif %}
    </table>
    <div class="pagination">
      <span class="step-links">
          {% if page_object.has_previous %}
              <a href="?occasion=daily_use&page=1">&laquo; 1ページ目に戻る</a>
              <a href="?page={{ page_object.previous_page_number }}">前のページ</a>
          {% endif %}
  
          <span class="current">
              ページ {{ page_object.number }} / {{ page_object.paginator.num_pages }}.
          </span>
  
          {% if page_object.has_next %}
              <a href="?page={{ page_object.next_page_number }}">次のページ</a>
              <a href="?page={{ page_object.paginator.num_pages }}">最後のページ &raquo;</a>
          {% endif %}
      </span>
  </div>
{% endblock content %}

templates/contents/testview2.html
{% extends 'contents/base.html' %}
{% load django_bootstrap5 %}

{% block header %}{% endblock header %}



{% block content %}
<h2>これはテストビュー2HTMLです</h2>

{% for item in object_list %}
{{ item.user }}<br>
{{ item.item_name }}<br>
{{ item.purchase_date }}<br>
{{ item.pricing }}<br>


{% endfor %}



{% endblock content %}